[tool.mypy]
python_version = "3.12"
strict = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
check_untyped_defs = true
show_error_codes = true
pretty = true

[[tool.mypy.overrides]]
module = ["aiogram.*", "dependency_injector.*"]
ignore_missing_imports = true

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "I", "UP", "B", "ANN", "ASYNC", "PL", "W"]
ignore = ["ANN101", "ANN102"]
fix = false

[tool.ruff.lint.isort]
known-first-party = ["navigator"]
force-single-line = false

[tool.pytest.ini_options]
python_files = ["trial.py"]
python_functions = ["digest", "extract"]
